---
title: "cxplot package"
author: "Isaac Neuhaus"
date: "`r Sys.Date()`"
output: 
    rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cxplot package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
library(cxplot)
```

## Reference

cxplot is wrapper for CanvasXpress that implements the grammar of the R
ggplot2 package written completely in Javascript.

## Plot basics 

All cxplot plots begin with a call to `var cxp = cxplot()`, supplying a
DOM target id to place the visualization, a default data and aesthetic
mappings, specified by `aes()`. You can also supply an additional
parameter with custom events. You then add layers, scales, coords and
facets with `cxp`.

|            |                              |
|:-----------|:-----------------------------|
| `cxplot()` | Create a new cxplot          |
| `aes()`    | Construct aesthetic mappings |

## Layers 

### Geoms 

A layer combines data, aesthetic mapping, a geom (geometric object), a
stat (statistical transformation), and a position adjustment. Typically,
you will create layers using a `geom_` function, overriding the default
position and stat if needed.

+----------------------------------+----------------------------------+
| `geom_abline()` `geom_hline()`   | Reference lines: horizontal,     |
| `geom_vline()`                   | vertical, and diagonal           |
+----------------------------------+----------------------------------+
| `geom_bar()` `geom_col()`        | Bar charts                       |
| `stat_count()`                   |                                  |
+----------------------------------+----------------------------------+
| `geom_bin_2d()` `stat_bin_2d()`  | Heatmap of 2d bin counts         |
+----------------------------------+----------------------------------+
| `geom_boxplot()`                 | A box and whiskers plot (in the  |
| `stat_boxplot()`                 | style of Tukey)                  |
+----------------------------------+----------------------------------+
| `geom_contour()`                 | 2D contours of a 3D surface      |
| `geom_contour_filled()`          |                                  |
|                                  |                                  |
| `stat_contour()`                 |                                  |
| `stat_contour_filled()`          |                                  |
+----------------------------------+----------------------------------+
| `geom_density()`                 | Smoothed density estimates       |
| `stat_density()`                 |                                  |
+----------------------------------+----------------------------------+
| `geom_density_2d()`              | Contours of a 2D density         |
| `geom_density_2d_filled()`       | estimate                         |
|                                  |                                  |
| `stat_density_2d()`              |                                  |
| `stat_density_2d_filled()`       |                                  |
+----------------------------------+----------------------------------+
| `geom_dotplot()`                 | Dot plot                         |
+----------------------------------+----------------------------------+
| `geom_hex()` `stat_bin_hex()`    | Hexagonal heatmap of 2d bin      |
|                                  | counts                           |
+----------------------------------+----------------------------------+
| `geom_histogram()` `stat_bin()`  | Histograms and frequency         |
|                                  | polygons                         |
+----------------------------------+----------------------------------+
| `geom_jitter()`                  | Jittered points                  |
+----------------------------------+----------------------------------+
| `geom_path()` `geom_line()`      | Connect observations             |
+----------------------------------+----------------------------------+
| `geom_point()`                   | Points                           |
+----------------------------------+----------------------------------+
| `geom_qq_line()`                 | A quantile-quantile plot         |
| `stat_qq_line()`                 |                                  |
|                                  |                                  |
| `geom_qq()` `stat_qq()`          |                                  |
+----------------------------------+----------------------------------+
| `geom_quantile()`                | Quantile regression              |
| `stat_quantile()`                |                                  |
+----------------------------------+----------------------------------+
| `geom_rug()`                     | Rug plots in the margins         |
+----------------------------------+----------------------------------+
| `geom_smooth()` `stat_smooth()`  | Smoothed conditional means       |
+----------------------------------+----------------------------------+
| `geom_text()`                    | Text                             |
+----------------------------------+----------------------------------+
| `geom_raster()`                  | Rectangles                       |
+----------------------------------+----------------------------------+
| `geom_violin()`                  | Violin plot                      |
| `stat_ydensity()`                |                                  |
+----------------------------------+----------------------------------+

### Scales 

Scales control the details of how data values are translated to visual
properties. Override the default scales to tweak details like the axis
labels or legend keys, or to use a completely different translation from
data to aesthetic. labs() and lims() are convenient helpers for the most
common adjustments to the labels and limits.

|                   |                  |
|-------------------|------------------|
| `xlim()` `ylim()` | Set scale limits |

### Facetting 

Facetting generates small multiples, each displaying a different subset
of the data. Facets are an alternative to aesthetics for displaying
additional discrete variables.

|                |                                    |
|----------------|------------------------------------|
| `facet_wrap()` | Wrap a 1d ribbon of panels into 2d |

Contents JavaScript Library Plot basics Layers Scales Facetting cxplot
is a part of CanvasXpress, a Javascript library for data analytics.
Learn more at canvasxpress.org.

Developed by CanvasXpress
